#!/bin/bash

# Code generated by chatGPT

# Iterative Fibonacci function
fib_iterative() {
    n=$1
    a=0
    b=1

    for ((i=0; i<n; i++)); do
        temp=$a
        a=$b
        b=$((temp + b))
    done

    echo $a
}

# Recursive Fibonacci function
fib_recursive() {
    n=$1

    if [ "$n" -le 0 ]; then
        echo 0
    elif [ "$n" -eq 1 ]; then
        echo 1
    else
        a=$(fib_recursive $((n - 1)))
        b=$(fib_recursive $((n - 2)))
        echo $((a + b))
    fi
}

# Check if an argument was provided
if [ -z "$1" ]; then
    echo "No argument provided – using demo values (0 to 20 in steps of 5):"
    for i in 0 5 10 15; do
        echo "n = $i"
        echo -n "  Iterative: "
        fib_iterative $i
        echo -n "  Recursive: "
        fib_recursive $i
        echo ""
    done
else
    n=$1
    echo "Calculating Fibonacci for n = $n"

    echo -n "Iterative: "
    fib_iterative $n

    echo -n "Recursive: "
    fib_recursive $n
fi
