#!/bin/bash

# Code generated by chatGPT 

# Default sort mode
SORT_MODE="ip"

# Parse options
while getopts "s:" opt; do
  case $opt in
    s)
      if [[ "$OPTARG" == "ip" || "$OPTARG" == "name" ]]; then
        SORT_MODE="$OPTARG"
      else
        echo "Invalid sort option. Use 'ip' or 'name'."
        exit 1
      fi
      ;;
    *)
      echo "Usage: $0 [-s ip|name]"
      exit 1
      ;;
  esac
done

# Check if nmap is installed
if ! command -v nmap &> /dev/null; then
    echo "nmap is not installed. Install it with:"
    echo "sudo apt install nmap"
    exit 1
fi

# Detect subnet automatically
SUBNET=$(ip -o -f inet addr show | awk '/scope global/ {print $4}' | head -n1)

echo "Scanning subnet: $SUBNET"
echo "-----------------------------------"

# Perform scan and collect results
RESULTS=$(nmap -sn $SUBNET | while read line; do
    if [[ $line == *"Nmap scan report for"* ]]; then
        if [[ $line == *"("* ]]; then
            name=$(echo "$line" | awk '{print $(NF-1)}')
            ip=$(echo "$line" | awk '{print $NF}' | tr -d '()')
        else
            ip=$(echo "$line" | awk '{print $NF}')
            name="Unknown"
        fi
        echo "$ip|$name"
    fi
done)

# Sort results
if [[ "$SORT_MODE" == "name" ]]; then
    SORTED=$(echo "$RESULTS" | sort -t '|' -k2)
else
    SORTED=$(echo "$RESULTS" | sort -t '|' -k1 -V)
fi

# Print results
echo "$SORTED" | while IFS="|" read ip name; do
    printf "IP: %-15s Name: %s\n" "$ip" "$name"
done

echo "-----------------------------------"
echo "Scan complete. Sorted by: $SORT_MODE"
