#!/bin/bash

# Code generated by chatGPT

# Generate a random number between 0 and 100
target=$(( RANDOM % 101 ))
echo "Welcome to the High-Low game! Try to guess the number between 0 and 100."

# -----------------------------
# Human game
# -----------------------------
human_attempts=0
while true; do
    read -p "Enter your guess: " guess

    # Check if input is a number
    if ! [[ "$guess" =~ ^[0-9]+$ ]]; then
        echo "Please enter a valid number."
        continue
    fi

    human_attempts=$((human_attempts + 1))

    if (( guess < target )); then
        echo "Too low!"
    elif (( guess > target )); then
        echo "Too high!"
    else
        echo "Correct! The number was $target. You took $human_attempts attempts."
        break
    fi
done

# -----------------------------
# Bot with binary search
# -----------------------------
bot_attempts=0
low=0
high=100

echo
echo "Now the bot will try to guess the number using binary search..."

while (( low <= high )); do
    bot_attempts=$((bot_attempts + 1))
    mid=$(( (low + high) / 2 ))

    echo "Bot guesses: $mid"

    if (( mid < target )); then
        echo "Too low!"
        low=$((mid + 1))
    elif (( mid > target )); then
        echo "Too high!"
        high=$((mid - 1))
    else
        echo "Bot guessed correctly! The number was $target."
        echo "Bot took $bot_attempts attempts."
        break
    fi
done

# -----------------------------
# Comparison
# -----------------------------
echo
echo "Comparison of attempts:"
echo "Human: $human_attempts attempts"
echo "Bot  : $bot_attempts attempts"
