#!/bin/bash

# Code generated by chatGPT

# Check if a file was provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

FILE="$1"

# Check if the file exists
if [ ! -f "$FILE" ]; then
    echo "File not found: $FILE"
    exit 1
fi

# Replace digits with text and output to console
sed \
    -e 's/0/zero/g' \
    -e 's/1/one/g' \
    -e 's/2/two/g' \
    -e 's/3/three/g' \
    -e 's/4/four/g' \
    -e 's/5/five/g' \
    -e 's/6/six/g' \
    -e 's/7/seven/g' \
    -e 's/8/eight/g' \
    -e 's/9/nine/g' \
    "$FILE"
