#!/bin/bash

# Code generated by chatGPT

# Default cities if no parameter is provided
DEFAULT_CITIES=("Hamburg" "Berlin" "Frankfurt" "Munich" "Kyiv" "Beijing")

get_weather() {
  CITY="$1"

  # Fetch weather from wttr.in in plain text format
  RESPONSE=$(curl -s "https://wttr.in/$CITY?format=j1")

  # Parse JSON using jq
  TEMP=$(echo $RESPONSE | jq -r '.current_condition[0].temp_C')
  DESCRIPTION=$(echo $RESPONSE | jq -r '.current_condition[0].weatherDesc[0].value')
  HUMIDITY=$(echo $RESPONSE | jq -r '.current_condition[0].humidity')
  WINDSPEED=$(echo $RESPONSE | jq -r '.current_condition[0].windspeedKmph')
  WINDDIR=$(echo $RESPONSE | jq -r '.current_condition[0].winddir16Point')

  echo "Current weather in $CITY:"
  echo "  Temperature: $TEMP °C"
  echo "  Weather: $DESCRIPTION"
  echo "  Humidity: $HUMIDITY%"
  echo "  Wind: $WINDSPEED km/h, $WINDDIR"
  echo "--------------------------------------"
}

# If a city parameter is provided, use it; otherwise use default cities
if [ -z "$1" ]; then
  for CITY in "${DEFAULT_CITIES[@]}"; do
    get_weather "$CITY"
  done
else
  get_weather "$1"
fi
